### PR TITLE
feat : button & image

### PR DESCRIPTION
**Pull request by sudipkundu999**
File structure:
components>button>button.css => contains CSS for button only
docs>component-presentation>button-presentation.css => contains CSS for presenting the button on the documentation site

### CODE REVIEW

**Review by sach10-create — APPROVED** [review]
Great use of variables and the use of naming conventions.

**Review by zoef-yt — APPROVED** [review]
Great clean code. Good to merge.

**Review by dcs-soni — APPROVED** [review]
Looks good to merge 👍

**Review by iRohitGaur — APPROVED** [review]
Nice work! Good to merge 👍🏻

**Pull request merged**
