### PR TITLE
feat : Cards

### PR DESCRIPTION
**Pull request by sudipkundu999**
File structure:
components>cards>cards.css => contains CSS for cards only
docs>component-presentation>cards-presentation.css => contains CSS for presenting the cards on the documentation site

P.S. some colors are used as "black", "white" intentionally

### CODE REVIEW

**Review by sach10-create — APPROVED** [review]
Great work with the responsiveness.

**Review by bhushannaikaroskar — APPROVED** [review]
Good naming conventions and CSS files are readable enough. Maybe look at spacing while writing code so that its occupied in less lines. For now I think its good to merge

**Comment by itsmebipul00** [comment]
Great work! You could use ems in media queries

**Review by zoef-yt — APPROVED** [review]
Looks good. Good to merge.

**Review by amartya-rs — COMMENTED** [review]
Good job Sudip.

**Pull request merged**
